export enum State {
  Abia = 'Abia',
  Adamawa = 'Adamawa',
  AkwaIbom = 'Akwa Ibom',
  Anambra = 'Anambra',
  Bauchi = 'Bauchi',
  Benue = 'Benue',
  Borno = 'Borno',
  Bayelsa = 'Bayelsa',
  CrossRiver = 'Cross River',
  Delta = 'Delta',
  Ebonyi = 'Ebonyi',
  Edo = 'Edo',
  Ekiti = 'Ekiti',
  Enugu = 'Enugu',
  FCT = 'FCT',
  Gombe = 'Gombe',
  Imo = 'Imo',
  Jigawa = 'Jigawa',
  Kebbi = 'Kebbi',
  Kaduna = 'Kaduna',
  Kano = 'Kano',
  Kogi = 'Kogi',
  Katsina = 'Katsina',
  Kwara = 'Kwara',
  Lagos = 'Lagos',
  Nassarawa = 'Nassarawa',
  Niger = 'Niger',
  Ogun = 'Ogun',
  Ondo = 'Ondo',
  Osun = 'Osun',
  Oyo = 'Oyo',
  Plateau = 'Plateau',
  Rivers = 'Rivers',
  Sokoto = 'Sokoto',
  Yobe = 'Yobe',
  Zamfara = 'Zamfara',
}

export enum Role {
  ADMIN = 'ADMIN',
  USER = 'USER',
  VENDOR = 'VENDOR',
  CUSTOMER = 'CUSTOMER',
  DESIGNER = 'DESIGNER',
  PUBLIC = 'PUBLIC',
}

export enum ItemStatus {
  PROCESSING = 'PROCESSING',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  SHIPPED = 'SHIPPED',
  RETURNED = 'RETURNED',
}
